# build with the following command
# sudo docker build -f Dockerfile_with_pymoab -t openmcworkshop/paramak_dependencies_with_pymoab . --no-cache
# run with the following command
# docker run -p 8888:8888 openmcworkshop/paramak_dependencies_with_pymoab


# FROM jupyter/minimal-notebook:10c9768598ab
FROM ubuntu:20.04

# this is required to install programs on the base image
USER root

RUN apt-get --yes update && apt-get --yes upgrade

RUN apt-get --yes install mpich
RUN apt-get --yes install libmpich-dev
RUN apt-get --yes install libhdf5-serial-dev
RUN apt-get --yes install libhdf5-mpich-dev
RUN apt-get --yes install libblas-dev
RUN apt-get --yes install liblapack-dev

RUN apt-get --yes install cmake
RUN apt-get -y install git
RUN apt-get --yes install hdf5-tools

USER $NB_USER

# MOAB Variables
ENV MOAB_BRANCH='Version5.1.0'
ENV MOAB_REPO='https://bitbucket.org/fathomteam/moab/'
ENV MOAB_INSTALL_DIR=$HOME/MOAB/


# MOAB Install
RUN cd $HOME && \
    mkdir MOAB && \
    cd MOAB && \
    git clone -b $MOAB_BRANCH $MOAB_REPO

RUN apt-get --yes install wget
# # Anaconda installing
RUN wget https://repo.continuum.io/archive/Anaconda3-2020.02-Linux-x86_64.sh

RUN bash Anaconda3-2020.02-Linux-x86_64.sh -b

RUN rm Anaconda3-2020.02-Linux-x86_64.sh

# # Set path to conda
ENV PATH /root/anaconda3/bin:$PATH

RUN conda install -c conda-forge -c cadquery cadquery=master

RUN pip install h5py
RUN pip install cython

RUN cd $HOME && \
    cd MOAB && \
    mkdir build && cd build && \
    cmake ../moab -DENABLE_HDF5=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$MOAB_INSTALL_DIR -DENABLE_PYMOAB=ON && \
    # cmake ../moab -DENABLE_HDF5=ON -DENABLE_MPI=off -DENABLE_NETCDF=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$MOAB_INSTALL_DIR && \
    make -j8 &&  \
    make -j8 install  && \
    cmake ../moab -DBUILD_SHARED_LIBS=ON && \
    make -j8 install && \
    # rm -rf $HOME/MOAB/moab $HOME/MOAB/build && \
    cd pymoab && \
    bash install.sh




# # pyrender install version 2.0-dev which breaks in docker
RUN pip uninstall pyglet 
# # this installs version 1.48 which works in docker
RUN pip install pyglet

USER root