# build with the following command
# sudo docker build -f Dockerfile_with_pymoab -t openmcworkshop/paramak_dependencies_with_pymoab . --no-cache
# run with the following command
# docker run -it openmcworkshop/paramak_dependencies_with_pymoab

FROM continuumio/miniconda3

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get --yes update

RUN apt-get install -y libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev \
                       freeglut3-dev libosmesa6 libosmesa6-dev \
                       libgles2-mesa-dev && \
                       apt-get clean

RUN conda install -c conda-forge -c cadquery cadquery=2

# RUN conda install -c cadquery -c conda-forge cadquery=master

# the following commands are needed for pymoab installation

RUN apt-get --yes install mpich libmpich-dev libhdf5-serial-dev && \
                          libhdf5-mpich-dev libblas-dev liblapack-dev

RUN apt-get -y install git
RUN apt-get -y install curl
RUN apt-get --yes install hdf5-tools

# MOAB Variables
ENV MOAB_BRANCH='Version5.1.0'
ENV MOAB_REPO='https://bitbucket.org/fathomteam/moab/'
ENV MOAB_INSTALL_DIR=$HOME/MOAB/


# MOAB download
RUN cd $HOME && \
    mkdir MOAB && \
    cd MOAB && \
    git clone -b $MOAB_BRANCH $MOAB_REPO

RUN pip install h5py
RUN pip install cython
RUN pip install cmake
RUN apt-get --yes install cmake

RUN cd $HOME && \
    cd MOAB && \
    mkdir build && cd build && \
    cmake ../moab -DENABLE_HDF5=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$MOAB_INSTALL_DIR -DENABLE_PYMOAB=ON && \
    # cmake ../moab -DENABLE_HDF5=ON -DENABLE_MPI=off -DENABLE_NETCDF=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$MOAB_INSTALL_DIR && \
    make -j8 &&  \
    make -j8 install  && \
    cmake ../moab -DBUILD_SHARED_LIBS=ON && \
    make -j8 install && \
    # rm -rf $HOME/MOAB/moab $HOME/MOAB/build && \
    cd pymoab && \
    bash install.sh && \
    python setup.py install
